name: group_5_project
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.0-191.0.dev <3.0.0"

dependencies:
  flutter_animated_button: 2.0.1
  flutter:
    sdk: flutter
  url_launcher: ^6.1.5
  getwidget: ^3.0.1
  number_slide_animation: ^0.2.1
  flutter_widget_from_html: ^0.8.5
  carousel_slider: ^4.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: DancingScript
      fonts:
        - asset: fonts/DancingScript-Regular.ttf
        - asset: fonts/DancingScript-Bold.ttf
          weight: 700
